### ISSUE TITLE
Errors in the versions 3.6.12 - 3.6.15

### ISSUE THREAD

**Issue by lua-rocks** [LuaLS/vscode-lua#80]
### How are you using the lua-language-server?

Visual Studio Code Extension (sumneko.lua)

### Which OS are you using?

Linux

### What is the issue affecting?

Other

### Actual Behaviour

Versions between `3.6.12` and `3.6.14` doesn't work at all in my VSCodium on Manjaro Linux.

Version `3.6.15` works, but showing broken error message:

![image](https://user-images.githubusercontent.com/82697845/222513602-1b20c739-3633-46bd-a0e3-b917f0524023.png)

![image](https://user-images.githubusercontent.com/82697845/222513496-e6ce0111-cbe7-453a-8234-5acafd18cdb6.png)

Version `3.6.11` works fine.

**Comment by carsakiller** [comment]
Hello, there were a series of issues when implementing the addon manager which completely broke the versions you mention. `3.6.15` should be working. Not sure why the log file wouldn't exist-can you open the `Output` panel and select `Lua Addon Manager` from the dropdown and send what you see in there?

**Comment by lua-rocks** [comment]
![image](https://user-images.githubusercontent.com/82697845/222527012-dee74989-6648-4f47-9137-4eea651314d2.png)

**Comment by carsakiller** [comment]
Hm, I am not sure if VSCodium supports all the same APIs as VS Code. It looks like it is failing when creating a log file.

**Comment by lua-rocks** [comment]
Yes, the directory `~/.config/VSCodium/logs/20230302T195814/window1/exthost/sumneko.lua/addonManager` is empty.

**Comment by lua-rocks** [comment]
Here is the content of `~/.config/VSCodium/logs/20230302T195814/window1/exthost/exthost.log`:

```
2023-03-02 19:58:15.745 [info] Extension host with pid 125043 started
2023-03-02 19:58:15.745 [info] Skipping acquiring lock for /home/luarocks/.config/VSCodium/User/workspaceStorage/d40d579047fe53977e033ee74dc61bbc.
2023-03-02 19:58:15.888 [info] ExtensionService#_doActivateExtension JohnnyMorganz.stylua, startup: false, activationEvent: 'onLanguage:lua'
2023-03-02 19:58:15.888 [info] ExtensionService#_doActivateExtension sumneko.lua, startup: false, activationEvent: 'onLanguage:lua'
2023-03-02 19:58:15.888 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-03-02 19:58:15.888 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
2023-03-02 19:58:15.888 [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
2023-03-02 19:58:15.888 [info] ExtensionService#_doActivateExtension yzhang.markdown-all-in-one, startup: false, activationEvent: 'onLanguage:markdown'
2023-03-02 19:58:15.889 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-03-02 19:58:15.889 [info] ExtensionService#_doActivateExtension funkyremi.vscode-google-translate, startup: true, activationEvent: '*'
2023-03-02 19:58:15.889 [info] ExtensionService#_doActivateExtension naumovs.color-highlight, startup: true, activationEvent: '*'
2023-03-02 19:58:16.148 [info] ExtensionService#_doActivateExtension vscode.markdown-math, startup: false, activationEvent: 'api', root cause: yzhang.markdown-all-in-one
2023-03-02 19:58:16.197 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-03-02 19:58:16.197 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-03-02 19:58:16.270 [info] Eager extensions activated
2023-03-02 19:58:16.278 [error] Error: ENOENT: no such file or directory, open 'home/luarocks/.config/VSCodium/logs/20230302T195814/window1/exthost/sumneko.lua/addonManager/19-58.log'
2023-03-02 19:58:16.318 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-03-02 19:58:16.318 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-03-02 19:58:16.318 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onStartupFinished', root cause: esbenp.prettier-vscode
2023-03-02 19:58:16.318 [info] ExtensionService#_doActivateExtension fcrespo82.markdown-table-formatter, startup: false, activationEvent: 'onStartupFinished'
2023-03-02 19:58:16.318 [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onStartupFinished'
2023-03-02 19:58:16.526 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-03-02 19:58:20.873 [error] EntryNotFound (FileSystemError): Unable to read file '/home/luarocks/.config/VSCodium/logs/20230302T195814/window1/exthost/sumneko.lua/addonManager/19-58.log' (Error: Unable to resolve nonexistent file '/home/luarocks/.config/VSCodium/logs/20230302T195814/window1/exthost/sumneko.lua/addonManager/19-58.log')
	at Yt._handleError (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:30142)
	at Object.readFile (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:29026)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-03-02 20:03:22.514 [info] Extension host terminating: received terminate message from renderer
2023-03-02 20:03:22.527 [error] Canceled: Canceled
	at new u (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:92736)
	at l._remoteCall (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:13769)
	at $.<computed>.N.charCodeAt.$.<computed> (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10315)
	at s._doExecuteCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:112905)
	at s.executeCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:112216)
	at E.registerCommand.description (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:111443)
	at s._executeContributedCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:113540)
	at s._doExecuteCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:112356)
	at s.executeCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:112216)
	at Object.executeCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:33764)
	at D (/opt/vscodium-bin/resources/app/extensions/git/dist/main.js:2:2055322)
	at f.invoke (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2559)
	at d.fire (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2137)
	at Object.h [as dispose] (/opt/vscodium-bin/resources/app/extensions/git/dist/main.js:2:2070159)
	at /opt/vscodium-bin/resources/app/extensions/git/dist/main.js:2:2074226
	at Array.forEach (<anonymous>)
	at g.dispose (/opt/vscodium-bin/resources/app/extensions/git/dist/main.js:2:2074212)
	at C.<anonymous> (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:13686)
	at C.dispose (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:13821)
	at C.<anonymous> (/opt/vscodium-bin/resources/app/extensions/git/dist/main.js:2:2057452)
	at C.dispose (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:13821)
	at k (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:12140)
	at f._deactivate (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:13198)
	at /opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:10372
	at Array.map (<anonymous>)
	at f._deactivateAll (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:10359)
	at f.terminate (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:10744)
	at h.terminate (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:1565)
	at p (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:19074)
	at /opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:16964
	at f.invoke (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2559)
	at d.fire (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2137)
	at p.fire (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:17066)
	at t._receiveMessage (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:23562)
	at /opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:20001
	at f.invoke (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2559)
	at d.fire (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2137)
	at h.acceptChunk (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:13890)
	at /opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:13020
	at Socket.t (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:28756)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) setContext undefined
2023-03-02 20:03:22.527 [info] Extension host with pid 125043 exiting with code 0
```

**Comment by carsakiller** [comment]
I believe this has been fixed in the commits I have just pushed, thanks for the help debugging!

Hopefully we can get the fix released soon 🙂
