### ISSUE TITLE
ERR [Extension Host] Error: Extension 'sumneko.lua' CANNOT use API proposal: extensionRuntime.

### ISSUE THREAD

**Issue by tiansin** [LuaLS/vscode-lua#93]
### Which OS are you using?

MacOS

### Expected Behaviour

Toggle Developer Tools

### Actual Behaviour

Toggle Developer Tools

### Reproduction steps

2. Click '...'
3. See error '...'

### Log
`
  ERR [Extension Host] Error: Extension 'sumneko.lua' CANNOT use API proposal: extensionRuntime.
Its package.json#enabledApiProposals-property declares: [] but NOT extensionRuntime.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api sumneko.lua
	at b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at get extensionRuntime [as extensionRuntime] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14104)
	at activate (/Users/myuser/.vscode/extensions/sumneko.lua-3.6.16-darwin-x64/client/out/extension.js:52:39)
	at Ui.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14833)
	at Ui.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14532)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:12550
	at async f.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
	at async f.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
	at async f.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)
console.ts:137 [Extension Host] Error: Extension 'sumneko.lua' CANNOT use API proposal: extensionRuntime.
Its package.json#enabledApiProposals-property declares: [] but NOT extensionRuntime.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api sumneko.lua
	at b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:44827)
	at get extensionRuntime [as extensionRuntime] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14104)
	at activate (/Users/myuser/.vscode/extensions/sumneko.lua-3.6.16-darwin-x64/client/out/extension.js:52:39)
	at Ui.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14833)
	at Ui.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14532)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:12550
	at async f.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
	at async f.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
	at async f.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)
`

**Comment by sumneko** [comment]
你的VSCode版本是多少

**Comment by carsakiller** [comment]
I have also seen this warning in the developer console of VS Code. I have seen it in multiple versions, included the latest (`1.76.0`)
![image](https://user-images.githubusercontent.com/61925890/223013888-96c26f06-785b-41f2-a973-6f5b83b279b5.png)

**Comment by carsakiller** [comment]
I have also seen this error in the developer console many times. I have seen it in many version of VS Code, including the latest (`1.76.0`)
![image](https://user-images.githubusercontent.com/61925890/223014243-e8fa1ae6-06b9-4e0e-a832-6441414d3421.png)

**Comment by tiansin** [comment]
> 你的VSCode版本是多少

```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z (4 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

**Comment by serg3295** [comment]
I can confirm this error. Steps to reproduce:
1. clone https://bitbucket.org/BoresExpress/nodemcu-tools/src/master/
2. run and debug => Run Extension
3. new window ' Extension Development Host' will open
4. in this window open any folder with enabled extension sumneko.lua 
5. see error.
![06-03-23_15-40](https://user-images.githubusercontent.com/75196080/223112965-b3e20f42-f9be-4103-a3fe-fb1cbe4c3b47.png)

**Comment by cmarincia** [comment]
It happens on Linux too.
```
Version: 1.76.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-14T07:56:58+11:00
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.5-229.current
Sandboxed: No
```

**Comment by cmarincia** [comment]
Should it be because of https://github.com/LuaLS/vscode-lua/blob/10d67344a8318a4d9ac98e59daa5e10ace10bcd1/client/src/languageserver.ts#L121 ?
